apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
# It will create a dedicated VPC for the cluster
metadata:
  name: kubelogs-cluster
  region: us-east-2
  version: "1.18"

availabilityZones: ["us-east-2a", "us-east-2b", "us-east-2c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t3.micro # This host cluster is using the smallest EC2
  ssh:
    enableSsm: true
  iam:
    withAddonPolicies: # Add-on policies to nodes
      autoScaler: true
      externalDNS: true
      certManager: true
      appMesh: true
      albIngress: true
      xRay: true
      cloudWatch: true

# Enable all of the control plane logs
cloudWatch:
 clusterLogging:
   enableTypes: ["*"]
