apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: prd
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - image: public.ecr.aws/i9m4f0j6/python-example-app-dr:latest
        name: example-app
        resources:
          requests:
            memory: "125Mi"
            cpu: "200m"
          limits:
            memory: "250Mi"
            cpu: "400m"
        ports:
          - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5