image:
  tag: 7.9.3
resources:
  limits:
    cpu: 0.5
    memory: 500Mi
  requests:
    cpu: 0.05
    memory: 20Mi

monitoring:
  enabled: false

overrideConfig:
  # Our own template with 1 shards and ISM
  setup.template:
    name: "filebeat-7.9.3"
    overwrite: false
    enabled: false
  # Disable ILM
  setup.ilm.enabled: false

  filebeat.autodiscover:
    providers:
      - type: kubernetes
        hints.enabled: true
        hints.default_config:
          enabled: true
          type: container
          paths:
            - /var/log/containers/*${data.kubernetes.container.id}.log
        templates:
            config:
              - type: docker
                containers.ids:
                  - "${data.kubernetes.container.id}"
  output.file:
    enabled: false
  output.elasticsearch:
    hosts: ["search-eksdemologging-rxlcbqa5gmmgpjuk6tr6266up4.us-east-1.es.amazonaws.com:443"]
    protocol: https
  output.elasticsearch.index: "dev-%{[agent.version]}-%{+yyyy.MM.dd}"